language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bhhan87/react-test -f ./client/Dockerfile.dev ./client

after_success:
  - docker build -t bhhan87/multi-client ./client
  - docker build -t bhhan87/multi-nginx ./nginx
  - docker build -t bhhan87/multi-server ./server
  - docker build -t bhhan87/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bhhan87/multi-client
  - docker push bhhan87/multi-nginx
  - docker push bhhan87/multi-server
  - docker push bhhan87/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-ap-northeast-2-852093670342
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
